language: java
install: mvn install
jdk:
  - openjdk11
services:
  - postgresql
before_script:
  - psql -c 'create database hospital;' -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'admin';" -U postgres