package me.kvq.hospitaltask.security;

import lombok.Getter;

@Getter
public enum Role {
    ADMIN("CREATE_PATIENT", "UPDATE_PATIENT", "DELETE_PATIENT", "SEE_ALL_PATIENTS",
            "CREATE_DOCTOR", "UPDATE_DOCTOR", "DELETE_DOCTOR", "SEE_ALL_DOCTORS",
            "CREATE_APPOINTMENT", "UPDATE_APPOINTMENT", "DELETE_APPOINTMENT", "SEE_ALL_APPOINTMENTS",
            "UPDATE_OFFWORK", "SEE_DOCTOR_UNAVAILABILITY", "UPDATE_TARIFF", "DELETE_TARIFF", "SEE_ALL_TARIFFS"),
    DOCTOR("SEE_ALL_PATIENTS", "SEE_OWN_APPOINTMENTS", "UPDATE_SELF"),
    PATIENT("SEE_ALL_DOCTORS", "UPDATE_SELF", "CREATE_OWN_APPOINTMENT", "DELETE_OWN_APPOINTMENT", "SEE_OWN_APPOINTMENTS",
            "SEE_DOCTOR_UNAVAILABILITY");

    private String[] permissions;

    Role(String... permissions) {
        this.permissions = permissions;
    }

}
